config:
  image_grid_width_sm: 640
  image_grid_width_md: 1080
  image_grid_width_lg: 1800
  image_width_sm: 1080
  image_width_md: 1800
  image_width_lg: 2400
  font_stack_system: >-
    -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu,
    Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", Arial, sans-serif,
    "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"
metadata:
  site_url: 'https://rommelnunez.github.io'
  site_title: ROMMEL
  site_subtitle_1: ''
  site_subtitle_2: NY / LA
  site_description: >
    Producer / Director / Photographer / Editor / Creative Director and
    co-founder @ [Baxtop](https://baxtop.agency).
  site_email: rommel@baxtop.agency
  site_social_url: 'https://instagram.com/its.rommel'
  site_icon_svg: /assets/uploads/favicon.svg
  site_icon_png: /assets/uploads/sig_black.PNG
  site_ga4_id: ''
  seo:
    site_title: Halide - Jamstack portfolio theme
    site_description: >-
      A customizable, minimalist portfolio website designed for photographers
      and still image creators.
    no_index: false
theme:
  theme_layout:
    space_scale: 50
  theme_colors:
    background: '#ffffff'
    text: '#101010'
    link: '#D0021B'
    background_dark: '#101010'
    text_dark: '#E1E1E1'
    link_dark: '#FFFFFF'
  theme_typography:
    font: Libre Franklin
    font_weight: 500
    font_scale: 100
    line_height_scale: 100
  theme_features:
    enable_dark_mode: true
    item_output_limit: 48
    transition_duration: 600
    show_project_year: true
    show_project_grid_titles: true
images:
  avif:
    enabled: false
    quality: 75
  webp:
    enabled: true
    quality: 75
  jpeg:
    enabled: true
    quality: 75
i18n:
  site_language: en
  site_social_title: Instagram
